//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTHome.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorHistory
    {
        public int Id { get; set; }
        public string SensorName { get; set; }
        public string SavedValue { get; set; }
        public System.DateTime TimeSaved { get; set; }
    }
}
